services:
  redis:
    image: redis:latest
    container_name: redis-difossa
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - ./redis:/data
    networks:
      - app-bridge

  app:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: ./builder/local/Dockerfile
    container_name: app-difossa
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  app-prod:
    profiles: ["prod"]
    build:
      context: .
      dockerfile: ./builder/prod/Dockerfile
    container_name: app-difossa-prod
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/var/www/html
    networks:
      - app-bridge

  webserver:
    image: nginx:stable-alpine
    container_name: nginx-difossa
    profiles: ["dev"]
    ports:
      - "8080:8080"
      - "5174:5173"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - app-bridge

  webserver-prod:
    image: nginx:stable-alpine
    container_name: nginx-difossa-prod
    restart: always
    profiles: ["prod"]
    ports:
      - "3001:80"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app-prod
    networks:
      - app-bridge

  mailpit:
    image: axllent/mailpit
    container_name: mailpit-difossa
    profiles: ["dev"]
    ports:
      - "8026:8025"
      - "1026:1025"
    networks:
      - app-bridge

  adminer:
    image: adminer
    container_name: adminer-difossa
    restart: always
    ports:
      - "8802:8080"
    networks:
      - app-bridge

networks:
  app-bridge:
    external: true
